### ISSUE TITLE
dataMaid -> datamaid

### ISSUE THREAD

**Issue by plpxsk** [ekstroem/dataMaid#12]
people will make mistakes and load this package into R with all lowercase. and it will fail

for usability, consider naming it all lowercase

**Comment by ekstroem** [comment]
We tried to use (lower) camel case naming consistently throughout the package, and having maid capitalized improves readability substantially at the cost of possibly introducing typing errors. 

Mixing cases is not uncommon in R packages names and thus the users should quickly become accustomed to it.

**Comment by plpxsk** [comment]
No tidyverse package uses camel case. All lowercase. 

But fair enough! Your call. Thanks for getting back so quickly!

**Comment by ekstroem** [comment]
That's true. But there really are a lot of other packages than the ones in the tidyverse. And gems like `purrr` (which I use quite a bit) opens up for missing an r so there's just no easy one-solution-fits-all.
