### ISSUE TITLE
Can I merge in a helper function?

### ISSUE THREAD

**Issue by epijim** [ekstroem/dataMaid#13]
Hello, this package is great. In my normal analysis though, I tend to most of the time need to just print a simple summary table. There is the spec package, but it doesn't seem to work. So I have the helper below, which I was inspired to wrap into a helper function (rather than just building it manually each time) after seeing your package.

The code is below - could this potentially be added to your package? If so I will do a pull request.

The justification is that in many analyses, we just need to print out a quick summary of what's in the derived dataset, as a table within the current Rmarkdown. In practice it looks like below,

![screen shot 2017-07-21 at 11 48 04](https://user-images.githubusercontent.com/2760096/28458586-869cde2e-6e0a-11e7-8b5f-88080bbc320c.jpg)

Is this in the scope of your package? 

```r
#' Simple summary table of a dataframe
#'
#' @param data The dataframe
#' @param output_type Output type required. For now, if not kable you get a dataframe
#' @return Summarise a dataframe in a table
#' @importFrom utils packageVersion sessionInfo capture.output packageDescription
#' @export
#' @examples
#' d_data <- data.frame(
#'   Time = as.Date('2009-01-01') + 0:9,
#'   Colours = rep(c("red", "blue"),5),
#'   Numbers = rnorm(10, 0, 10)
#' )
#' d_data$Potatoes <- rep(c("sweet",NA,"russet","french-fried","roasted"),2)
#' inlineSpecs(d_data)

inlineSpecs <- function(
  data,
  output_type = "kable"
  ) {
  # data checks
    # is it a dataframe?
    if (!is.data.frame(data) ) {
      ## tibble is automatically a data frame
      if (is.matrix(data)) {
        data <- as.data.frame(data)
      } else stop("inlineSpecs requires a data.frame, tibble or matrix as input")
    }

  # Name of dataframe
    # Extract the dataframe name
    dfname <- deparse(substitute(data))

  ## Summarise
    data_type <- class(data)
    data_rows <- nrow(data)
    col_names <- names(data)
    col_type <- sapply(data, class)
    col_missing <- sapply(data, function(x) sum(is.na(x)))
    col_minmax <- paste(apply(data,2,min,na.rm=TRUE),"to",apply(data,2,max,na.rm=TRUE))
    col_unique <- paste(apply(data,2,dplyr::n_distinct,na.rm=TRUE),"levels")

    output <- data.frame(
      Variable = col_names,
      Type = col_type,
      Missing = paste0(col_missing," ",round(100*col_missing/data_rows),"%"),
      MinMax = col_minmax,
      Levels = col_unique,
      stringsAsFactors = FALSE
    )
    output  <- dplyr::mutate(
      output,
      Details = ifelse(
        col_type %in% c("factor", "character"),
        Levels, MinMax
        )
      )

    output  <- dplyr::select(
      output,
      Variable,Type,Missing,Details
    )

    if (output_type == "kable") {
    output <- knitr::kable(
      output,
      caption = paste0("Summary of the ",data_type," ",dfname,". It has ",data_rows," rows"),
      row.names = FALSE
    )
    }
    return(output)
}
```

**Comment by ekstroem** [comment]
Hi.

Quick comment as I have a lousy connection until Monday. Any suggestions are welcome so if you have any ideas then please mention them and/or submit a PR. We did something like that for the version that can be found here on Github (in others words: if you have only tried the CRAN version then give the GitHub version a spin and tell us if it's something like that). 

PR are more than welcome but it's vacation time so it will likely be a few weeks before we can go through them.

**Comment by annennenne** [comment]
Expanding a bit on Claus' comments:

For interactive expolartion in the R-console, we suggest using the `summarize()` function directly on the data.frame. This gives the following result:
```
> summarize(d_data)
$Time
     Feature                   Result                  
[1,] "Variable type"           "Date"                  
[2,] "Number of missing obs."  "0 (0 %)"               
[3,] "Number of unique values" "10"                    
[4,] "Mode"                    "\"2009-01-01\""        
[5,] "Min. and max."           "2009-01-01; 2009-01-10"
[6,] "1st and 3rd quartiles"   "2009-01-03; 2009-01-08"

$Colours
     Feature                   Result    
[1,] "Variable type"           "factor"  
[2,] "Number of missing obs."  "0 (0 %)" 
[3,] "Number of unique values" "2"       
[4,] "Mode"                    "\"blue\""

$Numbers
     Feature                   Result         
[1,] "Variable type"           "numeric"      
[2,] "Number of missing obs."  "0 (0 %)"      
[3,] "Number of unique values" "10"           
[4,] "Median"                  "0.61"         
[5,] "1st and 3rd quartiles"   "-4.37; 6.43"  
[6,] "Min. and max."           "-16.06; 11.55"

$Potatoes
     Feature                   Result            
[1,] "Variable type"           "character"       
[2,] "Number of missing obs."  "2 (20 %)"        
[3,] "Number of unique values" "4"               
[4,] "Mode"                    "\"french-fried\""
```

In the newest update of `dataMaid` available here on Github, the report generated using `clean()` includes an overview table of the full dataset, similar to what you propose. The table for your example data looks like this in the pdf-report:
![image](https://user-images.githubusercontent.com/17068040/28773598-87b9a8ea-75ea-11e7-96e6-e9df313055f2.png)

**Comment by epijim** [comment]
Thanks @AnnePetersen1 and @ekstroem. It looks like everything I want is almost completely there - I just didn't see it in the version I installed.

summarize() is perfect, and gets all the data I was interested in. 

Many thanks, J
