### ISSUE TITLE
Add URL, BugReports fields to DESCRIPTION

### ISSUE THREAD

**Issue by richierocks** [ekstroem/dataMaid#2]
It's currently a little tricky to find this repo from the CRAN page.

Please add these lines to the `DESCRIPTION` file.

```
URL: https://github.com/ekstroem/dataMaid
BugReports: https://github.com/ekstroem/dataMaid/issues
```

**Comment by ekstroem** [comment]
Hi Richard.

Thank you for all your comments and suggestions. Please keep them coming. Some of them are already in the pipeline, and a few are waiting feedback from reviewers.
