### ISSUE TITLE
Report generation information not generating

### ISSUE THREAD

**Issue by alexhickok** [ekstroem/dataMaid#20]
I encountered this issue when using dataMaid to generate html and pdf summaries. Instead of the expected output at the end of the document, I see: 
Report generation information:
And a blank space afterwards.  Please let me know if you need more information!

I am running Windows 7 Pro, Rstudio version 1.0.143 
platform       x86_64-w64-mingw32          
arch              x86_64                      
os                 mingw32                     
system          x86_64, mingw32             
status                                     
major           3                           
minor          3.1                         
year             2016                        
month         06                          
day              21                          
svn rev        70800                       
language    R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair

**Comment by ekstroem** [comment]
Thanks Alex,

I tracked this down to a default setting by the `whoami` package which tries to identify the full name from the operating system. I added a default string in case the full name could not be determined from the system. The version on github should work now

**Comment by alexhickok** [comment]
Thanks Claus, I appreciate your work on this and great workshop at CSP!
