### ISSUE TITLE
Add data.frame level summary info

### ISSUE THREAD

**Issue by carlbfrederick** [ekstroem/dataMaid#22]
First, thanks for such a wonderful and versatile package.

The only feature/capability it doesn't have that I, and I suspect others, might want is the ability to add data.frame level summary information/notes to the output of `makeDataReport()` and `makeCodebook()`.

A little background about my use case: I work in state government and am responsible for fulfilling data requests. The ability to add variable labels and descriptions, along with all the other features of the codebooks are lightyears ahead of what we had been doing. Since, the end users of the data requests are often not familiar with the data, it is necessary to include some basic data.frame level information to help them use it.

**Proposed Solution**

I worked out a solution that is inspired by the variable labels/description. Users can add whatever text they want included in the report to the "label" attribute of the data.frame. Then it was trivial to add the following lines of code to the `makeDataReport()`.

        ## User added data.frame information
        if (!is.null(attr(data, "label"))) {
          writer(attr(data, "label"))
        }

If you are interested, I am happy to submit a pull request with this patch.

**Comment by ekstroem** [comment]
Sounds like a good idea very much along the same lines as the current way of handling the labels for the individual variables. Please submit a PR.

**Comment by carlbfrederick** [comment]
Ok, will do
