### ISSUE TITLE
makeCodebook can't specify mode

### ISSUE THREAD

**Issue by Jaeoc** [ekstroem/dataMaid#24]
Hi,

Tried to specify mode in the makeCodebook function, but it seems to be hardcoded (as far as I understand).:

```
makeCodebook(iris, mode = "summarize")

Error in makeDataReport(data, reportTitle = paste0("Codebook for ", dfname),  : 
  formal argument "mode" matched by multiple actual arguments
```
Result is that I still receive both "summarize", "visualize" and "check" in output which is undesirable. Same seems to be true if just running makeDataReport directly.

**Comment by annennenne** [comment]
Thanks for posting!

We have not allowed for the `mode` argument to be specified in `makeCodebook()`, so you are absolutely right in that it cannot be used. This is also how the function is documented.

However, you should be able to control it using the `makeDataReport()` function and I haven't been able to reproduce your error when calling this function, e.g.:
```
makeDataReport(iris, mode = "summarize")
``` 


If you want something that looks more like the codebook output, you can try
```
makeDataReport(iris,
               reportTitle="Codebook for iris", 
               file="codebook_iris.Rmd",
               codebook=TRUE,
               mode = c("summarize"),
               maxProbVals = Inf,
               listChecks = FALSE,
               smartNum = FALSE)
```

**Comment by ekstroem** [comment]
It was a bit of sloppy coding on my part with passing the arguments on to `makeDataReport`. Should be fixed in the version I'll push in a minute. Please test that different arguments work as expected.

**Comment by Jaeoc** [comment]
Seems to work, thanks for the fast fix.
