### ISSUE TITLE
makeCodebook option to remove variable list

### ISSUE THREAD

**Issue by Jaeoc** [ekstroem/dataMaid#25]
This package really appeals to me for making codebooks, but for my purposes currently prints too much information. An option to not print the variable list would be great.

**Comment by annennenne** [comment]
This is already achievable by using the `addSummaryTable` argument  inherited from `makeDataReport()`:
```  
makeCodebook(iris, addSummaryTable = FALSE)
```

**Comment by Jaeoc** [comment]
Thanks for the quick response, but that is not what I meant. 

Your suggestion removes the summary table, whereas I would like to remove the detailed information on each variable that is printed under the header "variable list". Sorry for any confusion.

**Comment by annennenne** [comment]
This is possible now using 
```
library(dataMaid)
makeCodebook(toyData, includeVariableList = FALSE)
```
