### ISSUE TITLE
"Special" characters encoding issues with the pdf report

### ISSUE THREAD

**Issue by 1DanielG** [ekstroem/dataMaid#31]
dataMaid::makeDataReport() produces report with wrong encoding.

The report for a name column (with Scandinavian characters) displays like below: 

&quot;Â HÃ¥kon &quot;, &quot;LangstrÃ¸m Heg&quot;, &quot;Pauline FÃ¸re

**Comment by ekstroem** [comment]
What operating system are you on? And it renders okay on my computer (a mac) with Scandinavian characters:

    DF <- data.frame(x=c("Æsel", "Ører", "Håkon", "Håkon"), y=c("rødgrød", "med", "fløde", "fløde"))

If you have *column names* with Scandinavian characters then there might be a problem

**Comment by 1DanielG** [comment]
Windows 10 , 
I fixed the encoding (UTF-8) before running the makeDataReport(), but same result

**Comment by annennenne** [comment]
It works fine here on Windows 7 too. Can you provide a minimal example that causes the error?

**Comment by 1DanielG** [comment]
It is bizarre,
I used ekstroem example:
DF <- data.frame(x=c("Æsel", "Ører", "Håkon", "Håkon"), y=c("rødgrød", "med", "fløde", "fløde"))

For Håkon I have “HÃ¥kon” and so on. I double checked MikTeX and I have updated babel-norwegian and babel-danish package as well.

**Comment by 1DanielG** [comment]
What is your RStudio encoding on Windows system? --> getOption("encoding")
It seems UTF-8 is not compatible for the nordic characters

**Comment by ekstroem** [comment]
How does the `DF` data frame from above look before you even pass it to `makeDataReport()`? When you print it or print one of the factors is it shown as it should?

    DF <- data.frame(x=c("Æsel", "Ører", "Håkon", "Håkon"), y=c("rødgrød", "med", "fløde", "fløde"))
    print(DF)
    DF$x

**Comment by 1DanielG** [comment]
Rstuido console displays it without problem:

> print(DF)
      x       y
1  Æsel rødgrød
2  Ører     med
3 Håkon   fløde
4 Håkon   fløde
> DF$x
[1] Æsel  Ører  Håkon Håkon
Levels: Æsel Håkon Ører

**Comment by 1DanielG** [comment]
I think I found the issue:
The problem arises when `"UTF-8"` is a default encoding in RStudio.
Changed the encoding to `"native.enc"` will solve a problem for `makeDataReport() `and pdf report renders okay with Scandinavian characters.

**Comment by ekstroem** [comment]
Closed as it seems to be an RStudio problem
