### ISSUE TITLE
Rotated axis labels for visualization

### ISSUE THREAD

**Issue by 1DanielG** [ekstroem/dataMaid#32]
Enhancement : 

It would be nice if the ggplot function has a rotated axis label in the final report for better readability.
ex:
... +
theme(axis.text.x = element_text(angle = 90, vjust=0, hjust=1))

**Comment by ekstroem** [comment]
Sadly, we cannot get a one-plot-works-everytime situation so the best option for that would be for you to provide your own visualisation tweaks so you can get it exactly the plot you want for your data. 

See the vignette on extending `dataMaid` to see examples of how to create your own functions for checking, summarizing and/or visualizing your data.

**Comment by annennenne** [comment]
I actually wrote a solution for this exact request in [another issue](https://github.com/ekstroem/dataMaid/issues/14). And I would like to emphasize that the code provided there is _not_ minimal: dataMaid extensions can be done much simpler!

I guess we should maybe consider including it in the package at some point, as it seems to keep popping up.
