### ISSUE TITLE
Capitalization inconsistent in "Report Was run from directory:"

### ISSUE THREAD

**Issue by justinmeyer** [ekstroem/dataMaid#37]
In dataMaid the phrase "Report Was run from directory:" sometimes has "was" with a capital w and sometimes with a lower case w. We are using the output from dataMaid and the difference between Was/was is causing a minor problem. We can work around it but it would be nice if it was consistent. Thanks!

**Comment by ekstroem** [comment]
What version of `dataMaid` are you running? And what OS?

I just grep'd the string `Was` in all the source files and it only appears as part of "Washington" (in some documentation). 

Is it something you can provoke systematically?

**Comment by justinmeyer** [comment]
Sorry for not giving you more information and sorry for bringing up this problem. I was using dataMaid 1.1.2 and it looks like that was the problem. I updated to the current version 1.2.0 and the capitalization has already been corrected in commit 662c39e07f08ec9541383ccba272d1ba4a6ec171. My mistake! Thanks for responding.

**Comment by ekstroem** [comment]
Must have been caused by running with different version (I didn't think to search through the commit trail to see if it actually could have been a version problem). 

Glad it got sorted out and thanks for reporting back with any inconsistencies you find. Please keep them coming.
