### ISSUE TITLE
Online tool "Error: line # did not have ## elements"

### ISSUE THREAD

**Issue by aalexandersson** [ekstroem/dataMaid#38]
Hello, thanks for your tool. I enjoyed your presentation at CSP 2018 :-) I am especially interested in the online tool.

Simplified text (txt) test data for the online tool:

```
ABC123456 JOHN DOE 1234567891234567891234567 SW 157TH ST MIAMI FL 33145
ABC222222 HELLO WORLD 123456789123456789123456 DOUGLAS RD EASTER HILL FL 33336 E
```

I notice two problems.
**Problem 1: "Error: line # did not have ## elements"**
The second line has an extra 12th variable for middle name "E". That should be allowed since middle names are often missing (empty string). But the online tool wrongly gives and error. This is the error message: 

Error: line 1 did not have 11 elements
(see screenshot below for details)

![datamaid_screenshot](https://user-images.githubusercontent.com/20467610/52068840-79ef1f80-254b-11e9-88b8-dad704d2a21b.PNG)

If that problematic line instead was line 2, then the error would be "line 2 did not have 11 elements" (I omit another screenshot to save space). As a possible fix, I tried Comma-separated (csv) but then I get one variable instead of wanted 12 variables. 

**Problem 2 (feature wish): Tool does not recognize fixed-length format**
I actually have text in the fixed-length column-specified format. In the test example, 1234567891234567891234567 is a fake combination of Social Security Number, Date of Birth, Sex and Race, and Street number. Another similar example, first name always begins in column 16 but the tool does not recognize that feature.

**Comment by annennenne** [comment]
Thanks for the interest in the app!

I'm afraid that your problem is what I would consider a corrupted data file. If data is stored in a txt file, the columns should be separated by spaces while the rows should be separated by new lines. If you want R to read in an empty field in a txt file, you should explicitly put in an empty string in the file, e.g.
``` 
ABC123456 JOHN DOE 1234567891234567891234567 SW 157TH ST MIAMI FL 33145 ""
ABC222222 HELLO WORLD 123456789123456789123456 DOUGLAS RD EASTER HILL FL 33336 E
``` 

csv files, on the other hand, have commas (or sometimes semicolons) between variables. So if you want to use the csv input option, your file should be a proper csv file, e.g.
 ``` 
ABC222222, HELLO, WORLD, 123456789123456789123456, DOUGLAS, RD, EASTER, HILL, FL, 33336, E
ABC123456, JOHN, DOE, 1234567891234567891234567, SW, 157TH, ST, MIAMI, FL, 33145,  
``` 

Concerning your feature request, I am not exactly sure what you are asking for. Can you provide more details on what you would like?

 If you are using txt or csv files, you can provide column names by making them the first line in the file and then checking off "First data line contains the variable names" in our app. But again, you need to separate the variable names in the same way as the rest of the rows in the data file (space or comma). Here's an example where I have divided your data into 9 variables and stored it as a csv file:
``` 
ID, first_name, last_name, longNumber, address, city, state, zip, middle_name
ABC222222, HELLO, WORLD, 123456789123456789123456, DOUGLAS RD, EASTER HILL, FL, 33336, E
ABC123456, JOHN, DOE, 1234567891234567891234567, SW 157TH ST, MIAMI, FL, 33145,  
```

**Comment by aalexandersson** [comment]
Thank you. I am asking for these two options in txt files:
1. An option to read in an empty field without having to manually first correct it with ""

2. An option to read the "fixed-column" format, for example, as in [Stata](https://www.stata.com/support/faqs/data-management/reading-fixed-format-data/).

More examples of fixed-column format here:
https://www.stata.com/manuals13/dinfixfixedformat.pdf

**Comment by annennenne** [comment]
Regarding your first suggestion: I don't think we will try to accomodate this. I think your data file is corrupted and without proper use of column separators, I don't think any computer program can read it correctly. You both use space as a column separator and as a normal blank space and I can't see how a computer should know when to interpret it as one or the other. 

Regarding your second suggestion: I'm afraid this is not really compatible with R. In R, data formats (classes in R terminology) are very liberal, so in standard R, it's not possible to restrict a variable to only contain e.g. 10 character strings. But do note that the app should work for Stata data, so you can load and prepare your data in Stata if you'd like.

**Comment by aalexandersson** [comment]
Thank you. The first suggestion is moot (irrelevant) if you implement the second suggestion of fixed-column text format. So, what I really want is fixed-column text format to be implemented. The R function [read_fwf](https://github.com/tidyverse/readr/blob/master/R/read_fwf.R), which is part of tidyverse, can read fixed-width text data in R. It is "just" a matter if implementing the R function into your R app. In effect, if you decide to implement this option, then there would be two txt formats: space-delimited (exists now) and fixed-column width (could be implemented by calling read_fwf function). 

Also, though the example data is hypothetical the user need is real. I work at a US cancer registry. US cancer registries, or cancer registries belonging to NAACCR to be precise, require fixed-column text data. (The fixed-width standard at NAACCR will be replaced by XML but that is a detail I am not concerned about yet for our possible use of your app).

Thank you for mentioning Stata as an input option. Not every cancer researcher use Stata (many prefer SAS or R instead) but it is certainly an option for some; I prefer Stata myself.

**Comment by annennenne** [comment]
The link you provided above to Stata functions was about _fixed column_ formats, and the function you are linking to now is for _fixed width_ files. These are two different things. While I understand the usefulness of _fixed column_ formats, I stand by my claim that this is not compatible with R. However, you are right that it is definitely possible to read _fixed width files_ but I fail to see when this should be useful. Then all values in a variable in your dataset would have to take up the same number of characters (possibly by including a lot of white space). The example dataset you provided could not be read correctly as a fixed width file without a lot of editing. Moreover, the user would have to manually specify the widths of all the columns in the data, which would be very tedious in a point-and-click tool like the dataMaid online tool. In order for the online tool to be as user-friendly as possible, we would like to keep the options at a minimum, especially advanced features that most users are not interested in. 
Therefore, we will stick with delimiter-based data in the online tool. 

In any case, I think converting data from fixed width format to delimiter-based is very easy in R, and I am sure there are options in Stata and SAS as well. As soon as you have the data in the Stata (.dta) or SAS (.sas7bdat) formats, you can just use that in the online tool. So I think there is no problem as long as the user masters (i.e., knows how to load and save data in) either R, Stata or SAS.

**Comment by aalexandersson** [comment]
I mostly wish (an online version of) dataMaid to handle _fixed-width files_, which Stata also refers to as fixed format with a data dictionary.  If implemented, the dataMaid user would only have to upload the file, just a few point-and-clicks as now. Then, dataMaid would report the results, just as now. 

OK, you made the decision not to add this feature and I understand why. Fixed-width files have two big problems in my view. Such files are 1) increasingly rare, and 2) relatively difficult to work with. I happen to work in an area where fixed-width files are still common: U.S. cancer registries. An obvious example, perhaps, is the [NAACCR data dictionary](http://datadictionary.naaccr.org/?c=10). Another typical example is the finder file for probabilistic record linkage because the fixed-width format is one of few supported formats in the two most popular software: [Link Plus](https://www.cdc.gov/cancer/npcr/tools/registryplus/lp.htm) and [Match*Pro](https://surveillance.cancer.gov/matchpro/download). 

Best wishes in making the online tool online (in configuring the R server). Any plans for this in 2019?

**Comment by annennenne** [comment]
Thank you very much! We are currently having another go on making the online version work properly, and hopefully we will succeed soon.
