### ISSUE TITLE
Preserve order of factor levels

### ISSUE THREAD

**Issue by sebastien-foulle** [ekstroem/dataMaid#46]
Barcharts list factor levels in alphabetical order. The problem comes from dataMaid:::standardVisualCFLB , a solution might be to replace the line

`v<- escapeRStyle(na.omit(v)) `

with something like

```
v = na.omit(v)
  modalites = levels(v)
  if (is.null(modalites)) {
    v <- dataMaid:::escapeRStyle(v)
  } else {
      new_modalites = dataMaid:::escapeRStyle(modalites)
      levels(v) = new_modalites
    }
```
Have a good day

**Comment by annennenne** [comment]
Thank you for notifying us of this issue! I have fixed it now in the github version of the package.
