### ISSUE TITLE
Error when calling dataMaid::makeCodebook without library(dataMaid)

### ISSUE THREAD

**Issue by jelger12** [ekstroem/dataMaid#47]
When you call the makeCodebook function directly without loading the dataMaid package, I get an error
```
> dataMaid::makeCodebook(data.frame(a = letters))
Error in makeDataReport(data = data.frame(a = letters), reportTitle = "Codebook for data.frame(a = letters)",  : 
  could not find function "makeDataReport"
```

This is a problem when using an internal package which uses the makeCodebook function.

The following code doesn't throw an error
```
> library(dataMaid)
> makeCodebook(data.frame(a = letters))
```

It looks like the problem is in the eval.parent function
https://github.com/ekstroem/dataMaid/blob/master/R/makeCodebook.R#L69

**Comment by ekstroem** [comment]
Should be fixed with the update I just pushed. Please check

**Comment by jelger12** [comment]
I've checked the update and it's fixed. Thanks!
