### ISSUE TITLE
Proposal: Show first and last problematic values to see low and high outliers.

### ISSUE THREAD

**Issue by skranz** [ekstroem/dataMaid#51]
Just found dataMaid and it seems a very useful package for data cleaning. Here is just a small proposal. If a variable has too many outliers, dataMaid currently only shows the first values. E.g.  here is an example for a variable with `Min. and max. 1300; 215245`:
```
 Note that the following possible outlier values were detected: "1300", "1470", "1476", "1477",
 "1484", "1488", "1491", "1495", "1504", "1526" (126 additional values omitted).
```

Given that the 126 variables are omitted, we cannot see from the output whether also large variables are considered as outliers. Below is a proposal to rewrite of the function `printProblemValues` such that the first and last problematic values are shown and the ommited values are indicted with `...` in the center. The output for the data set above then is:

```
Note that the following possible outlier values were detected: "1300", "1470", "1476", "1477",
 "1484", . . . ,"70761", "115149", "159000", "164660", "215245" (126 values omitted).
```
This makes clear that low as well as large values are tagged as potential outliers.

My modified version of the function simply is the following:

```r
printProblemValues <- function(problemValues, nMax = Inf) {
    problemValues <- escapeRMDStyle(sort(problemValues, na.last = TRUE))
        ##NOTE: sort removes NaNs if not told explicitly not to by use of the na.last-argument
    nVals <- length(problemValues)
    
    # Show first and last problematic values
    # Only the code in this if condition has been added.
    # Otherwise the function is as before
    if (nMax > 1 & nMax < nVals) {
      nLeft = ceiling(nMax / 2)
      nRight = floor(nMax / 2)
      strLeft = paste0(paste0("\\\"", problemValues[1:nLeft], "\\\""),
        collapse=", ")
      strRight = paste0(paste0("\\\"", problemValues[(nVals-nRight+1):nVals], "\\\""),collapse=", ")
      extraStr <- paste(" (", nVals-nMax, " values omitted)", sep="")
      return(paste0(strLeft, ", ..., ",strRight,extraStr))
    }
    
    extraStr <- ""
    if (nMax < nVals) {
      if (nMax == 0) {
        problemValues <- ""
        extraStr <- paste(nVals-nMax, "problematic value(s) omitted")
      } else {
        problemValues <- problemValues[1:nMax]
        extraStr <- paste(" (", nVals-nMax, " additional values omitted)", sep="")
      }
    }
    paste(paste(paste("\\\"", problemValues, "\\\"", sep=""),
                collapse=", "), extraStr, sep="")
}
```

**Comment by annennenne** [comment]
I think this is an excellent suggestion - it's a lot more informative like that. Let's do it. 

@skranz Are you interested in doing this as a pull request or would you rather have me implement it myself? 

A notes for whoever ends up implementing it, me or you:
- For backwards reproducibility, we should also keep the old option and then control it via an argument for `makeDataReport()` (probably actually via `check()` and then passed along to `makeDataReport()`).

**Comment by skranz** [comment]
Great. It is probably easier if you implement it, given that you also want to pass an option to `makeDataReport`. I only changed the code shown above.
