### ISSUE TITLE
Suspected bug in identifyNums.R

### ISSUE THREAD

**Issue by hbearr** [ekstroem/dataMaid#53]
Dear all,

Thank you for making your work available to the community.

I think the function `identifyNums()` in `identifyNums.R ` might not be behaving as expected when the argument `v` consists of only digits or `.`, and when all its values have more than one `.` character within. In this case I don't think this vector should be identified as a number. 

The statement at line 58:
` v <- gsub("\\.{1}", "", v) #remove decimal points`
strips all `.` characters from each string, not just the first one. It probably should be replaced by:
` v <- sub("\\.{1}", "", v) #remove first decimal point`
which only strips the first occurrence of `.`.

*Reproducible example*:
Consider the following `test` vector: `"1.1.1",  "1.2.1",  "1.3.1", ...` (not meant to be a number, just some sort of ID made up of composite parts):
`test = sprintf("1.%d.1", 1:13)`
where the length of the vector is 1 more than the default value (12) for `nVals` in the call to `identifyNums()`.
Then, calling `identifyMissing()` leads to the following:
```
> identifyMissing(v = test)
No problems found.Warning message:
In identifyMissingCF(v, nMax = nMax) : NAs introduced by coercion
> 
```

I think this problem goes away if `gsub()` is replaced by `sub()` as shown above.

Best regards,
Hervé

**Comment by ekstroem** [comment]
Thanks! Should be fixed in the version just pushed to github

**Comment by hbearr** [comment]
Thank you very much.

Best regards,
Hervé
