### ISSUE TITLE
none of the haven_labelled variables appear in report unless first converted via as_factor

### ISSUE THREAD

**Issue by ericpgreen** [ekstroem/dataMaid#54]
I'm taking dataMaid for a spin. It looks really impressive!

When I create my report, all variables are captured in the dimensions and checks, but none of the variables with the class `"haven_labelled" "vctrs_vctr"     "double"` are included in the summary table or variable list, even if I specify `labelled_as= "factor"`. 

However it will work if I first convert all `labelled::is.labelled` variables via `labelled::as_factor`. 

Is this working as intended, or should I be able to skip the conversion step?

**Comment by annennenne** [comment]
Thank you! 

`double` (which are identical to `numeric` in R) and `haven_labelled` should be supported. I am surprised to hear they are not included in the variable list. Could you provide a copy of your outputted data report or a minimal example that produces the error? 

Wrt. `vctrs_vctr`; this class is not supported by `dataMaid` so you will need to manually specify how it should be handled. You can do that using the argument `treatXasY`. For example, if you want `vctrs_vctr` variables to be treated like numeric variables, the code will be something like this

``` 
makeDataReport(dataset, treatXasY = list(`vctrs_vctr` = "numeric"))

**Comment by ericpgreen** [comment]
Thanks, @annennenne. Here's a small example:

```
library(tidyverse)
library(dataMaid)
library(labelled)
codebook_data <- rio::import("https://osf.io/s87kd/download", "csv")

val_labels(codebook_data$gender) <- c("male" = 1, "female" = 2)
val_labels(codebook_data$education) <- c("in high school" = 1,
                                         "finished high school" = 2,
                                         "some college" = 3, 
                                         "college graduate" = 4, 
                                         "graduate degree" = 5)

codebook_data <- codebook_data %>%
  select(gender, education, age) 

# works if I run this 
#codebook_data <- codebook_data %>%
#  mutate_if(is.labelled, as_factor)

makeDataReport(codebook_data, codebook = TRUE, replace=TRUE, output = "html",
               treatXasY = list(`vctrs_vctr` = "numeric"))
```

**Comment by annennenne** [comment]
I think I have found the issue and fixed it. However, we are actually in the process of renaming this package to `dataReporter` - the new version has just arrived on CRAN earlier this week. Therefore, we are not going to update `dataMaid` any further. But I have fixed the bug in the development version of `dataReporter`, which you can install from here:
```
devtools::install_github("ekstroem/dataReporter")
```
And you should be able to produce the codebook from your example like this:
```
makeDataReport(codebook_data, codebook = TRUE, replace=TRUE, output = "html")
```
I had misunderstood what classes your variables were - as they are _also_ `haven_labelled` they are supported and you don't need to use the `treatXasY` argument. 

Also, note that `makeDataReport()` with `codebook = TRUE` is not the "full" codebook version of the data report - if you want that, you need to use the `makeCodebook()` function. 

Let me know if it's still not working for you.
