### ISSUE TITLE
Suppress "Report generation information"

### ISSUE THREAD

**Issue by dataning** [ekstroem/dataMaid#57]
Hi, 

I love the package! I have one question - Is there a way to suppress/hide "Report generation information" at the end of the report. If the report is being distributed among my team, it would be a bit embarrassing to show how I name my local drive, pathways and other things :)

**Comment by annennenne** [comment]
Currently, this is not supported. 

You can work around the problem by manually removing the information before rendering the report to pdf/html. The workflow would go like this (example on the cars dataset):

```
data(cars)
library(dataReporter)
makeDataReport(cars, render = FALSE)
```

Then manually open `dataReporter_cars.Rmd` and remove the information you don't want. And then run:

```
render("dataReporter_cars.Rmd")
``` 

There is probably also some clever way to delete the relevant lines from the `.Rmd` document without doing it manually. 

I'll consider making it possible to opt out of "Report generation information" altogether next time we do an update.

**Comment by ekstroem** [comment]
Also ... please consider moving to the `dataReporter` package as `dataMaid` will be deprecated and will not receive future  updates besides fixing errors.

**Comment by dataning** [comment]
Thanks @annennenne - that's a clever way to do it - using rmarkdown to amend the information. 

and @ekstroem - thanks for the reminder - it's just the issue section in dataReporter is so clean and I didn't want to become the first one to break it but I'd do it next time :)
