### ISSUE TITLE
decoding failures

### ISSUE THREAD

**Issue by lucaseosilva** [ekstroem/dataMaid#58]
first, congratulations on the package! it's very useful and practical.

however, I would like to leave a suggestion for future implementations: work with multiple types of encoding.

the package works great for english, for example. however, if we use Latin languages (portuguese, spanish and french) there are many errors in encoding the .md file.

**Comment by annennenne** [comment]
Thank you for the suggestion. I think what encoding works may depend on your own default settings. 

Do you know at which state the encoding is messed up? First, are data loaded in correctly? And if so, would you mind checking if the encoding problem occurs before the report is rendered? 

I.e. run something like
```
makeDataReport([your dataset], render = FALSE)
```
and then open and inspect the thereby produced dataReport_[your dataset].Rmd file and see if the encoding is preserved at this state? 

Btw, note that the package has been renamed to dataReporter and that we no longer maintain dataMaid. You can download dataReporter from CRAN as well.

**Comment by lucaseosilva** [comment]
thanks for your reply!

makeDataReport() function generates the .rmd file perfectly. the problem is the conversion of the content in the file. there is an error converting the text in latin1 to UTF-8.

for example:

the word CORAÇÃO (latin1) present in the dataframe, is CORA??O (UTF-8) in the .rmd file 

therefore it is not rendered because of these special characters

**Comment by annennenne** [comment]
I am not sure if this is a dataReporter issue or if it is a problem with your settings. Could you check your default encoding?
```
options("encoding")
```

**Comment by lucaseosilva** [comment]
![image](https://user-images.githubusercontent.com/23392367/146459751-dc4a059a-cd68-4662-9e0e-ed067c88c985.png)

**Comment by annennenne** [comment]
That should be correct. But would you check what happens if you change it before running makeDataReport?
So something like 
```
oldOptions <- options()
options(encoding = "latin1")
makeDataReport([your dataset])
options(oldOptions)
```

**Comment by lucaseosilva** [comment]
yeah!

now, it works!

i put `options(encoding = "UTF-8")` before run `makeCodebook()` and the conversion text process was perfectly!

really thanks!

**Comment by annennenne** [comment]
You're welcome!
