### ISSUE TITLE
Support raw columns

### ISSUE THREAD

**Issue by richierocks** [ekstroem/dataMaid#8]
Raw columns cause errors in `clean()`.

```r
d <- data.frame(x = as.raw(rep(1:2, 5)))
clean(d, replace = TRUE)
## Error in UseMethod("check") : 
##   no applicable method for 'check' applied to an object of class "raw"
## Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
##   invalid 'row.names' length
## Data cleaning is finished. Please wait while your output file is being rendered.
```

**Comment by annennenne** [comment]
As of now, dataMaid supports the following variable types: `factor`, `character`, `labelled`, `numeric`, `integer`, `logical` and `Date`. Of course, this also implies that we support other variable classes that inherit from these classes. 

When using specialized, and thus more restrictive, classes, the risk of inducing errors in the variable becomes smaller. Therefore, we have mainly focused on the rather general data types of R, where the risk of mistakes is the greatest. 

However, I will add an update such that the user can specify how non-supported variable classes should be handled by reference to the supported variable classes. This means that one can e.g. specify that `raw` variables should be handled as `character`, `complex` as `numeric` etc. I will also catch remaining, non-supported variables with a function similar to the check for empty- and key variables, so the data cleaning does not crash.

Once again, thanks for your input.

**Comment by annennenne** [comment]
I guess I have to practice my Github referencing skills, but I implemented the update described above [here](https://github.com/ekstroem/dataMaid/commit/e03741c6e12147e0bbf50df9918d7a9a910f4b71).
